export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';

export const SAVE_TO_FAVORITES = 'SAVE_TO_FAVORITES';
